### ISSUE TITLE
Unable to build binary

### ISSUE THREAD

**Issue by jakep82** [UsbCANConverter-UCCbasic/UCCB_GS_Embedded#2]
I'm unable to build a binary from the fix_queue branch of your firmware which I need for my project.  Are able to build and publish a firmware file that includes this queue fix?

**Comment by Lukasz-Juranek** [comment]
please try this one https://github.com/UsbCANConverter-UCCbasic/UCCB_GS_Embedded/releases/tag/0004

**Comment by jakep82** [comment]
I need to do some more testing, but this appears to be working great. Thanks for posting this.
